export {Header} from './Header'
export {Logo} from './Logo'
export {Button} from './Button'
export {Parrot} from './Parrot'
export {TextInput} from './Input'
export {Post} from './Post'
export {CustomSlider} from './Slider'
export {Footer} from './Footer'